/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzsin_eyer_gb28181_CInterface */

#ifndef _Included_com_zzsin_eyer_gb28181_CInterface
#define _Included_com_zzsin_eyer_gb28181_CInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzsin_eyer_gb28181_CInterface
 * Method:    eyer_gb_get_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zzsin_eyer_gb28181_CInterface_eyer_1gb_1get_1version
  (JNIEnv *, jclass);

/*
 * Class:     com_zzsin_eyer_gb28181_CInterface
 * Method:    eyer_gb_sipserver_init
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_zzsin_eyer_gb28181_CInterface_eyer_1gb_1sipserver_1init
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zzsin_eyer_gb28181_CInterface
 * Method:    eyer_gb_sipserver_uninit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyer_gb28181_CInterface_eyer_1gb_1sipserver_1uninit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zzsin_eyer_gb28181_CInterface
 * Method:    eyer_gb_sipserver_start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyer_gb28181_CInterface_eyer_1gb_1sipserver_1start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zzsin_eyer_gb28181_CInterface
 * Method:    eyer_gb_sipserver_stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyer_gb28181_CInterface_eyer_1gb_1sipserver_1stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zzsin_eyer_gb28181_CInterface
 * Method:    eyer_gb_sipserver_set_passive_callback
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyer_gb28181_CInterface_eyer_1gb_1sipserver_1set_1passive_1callback
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_zzsin_eyer_gb28181_CInterface
 * Method:    eyer_gb_sipserver_query_devices
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyer_gb28181_CInterface_eyer_1gb_1sipserver_1query_1devices
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_zzsin_eyer_gb28181_CInterface
 * Method:    eyer_gb_device_list_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zzsin_eyer_gb28181_CInterface_eyer_1gb_1device_1list_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_zzsin_eyer_gb28181_CInterface
 * Method:    eyer_gb_device_list_uninit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyer_gb28181_CInterface_eyer_1gb_1device_1list_1uninit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zzsin_eyer_gb28181_CInterface
 * Method:    eyer_gb_device_list_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyer_gb28181_CInterface_eyer_1gb_1device_1list_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zzsin_eyer_gb28181_CInterface
 * Method:    eyer_gb_sipserver_passive_callback_init
 * Signature: (Lcom/zzsin/eyer/gb28181/SIPPassiveCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_zzsin_eyer_gb28181_CInterface_eyer_1gb_1sipserver_1passive_1callback_1init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_zzsin_eyer_gb28181_CInterface
 * Method:    eyer_gb_sipserver_passive_callback_uninit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyer_gb28181_CInterface_eyer_1gb_1sipserver_1passive_1callback_1uninit
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
